# Generated by Django 3.0.8 on 2020-07-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_field', models.IntegerField(default=0)),
                ('related_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_character_score', to='api.Score')),
            ],
        ),
    ]
