# Generated by Django 3.0.8 on 2020-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug_item',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
