# Generated by Django 3.0.8 on 2020-07-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_slug_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
    ]
