# Generated by Django 3.0.8 on 2020-07-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='related_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_character_score', to='api.Character'),
        ),
    ]
